name: Node.js Package on Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use node.js ${{matrix.node-version}}
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

  publish-gpr:
    needs: build
    if: github.event.push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
